#!/usr/bin/env node
// FILENAME: install.js
// Fluxus Language Installation Script - ENHANCED VERSION

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

class FluxusInstaller {
    constructor() {
        this.projectRoot = __dirname; 
        this.globalInstall = process.argv.includes('--global');
        this.installDir = this.globalInstall ?
            this.findGlobalInstallDir() :
            this.projectRoot;
    }

    findGlobalInstallDir() {
        const possibleDirs = [
            '/data/data/com.termux/files/usr/bin', // Termux specific
            '/usr/local/bin',                      // Standard Linux/macOS
            '/usr/bin',                            // Secondary Linux
            process.env.HOME ? path.join(process.env.HOME, '.local', 'bin') : null,
        ].filter(Boolean);

        for (const dir of possibleDirs) {
            if (fs.existsSync(dir)) {
                try {
                    fs.accessSync(dir, fs.constants.W_OK); 
                    console.log(`📁 Using writable installation directory: ${dir}`);
                    return dir;
                } catch (e) {
                    console.log(`   - Directory exists but is not writable: ${dir}`);
                }
            }
        }
        console.log('⚠️  No writable global directory found. Proceeding with local installation.');
        return this.projectRoot;
    }

    installGlobal() {
        const targetBin = path.join(this.installDir, 'fluxus');
        
        if (this.installDir === this.projectRoot) {
            console.log('❌ Global installation skipped: No writable global directory found.');
            this.globalInstall = false; 
            return;
        }

        // ENHANCEMENT: Verify CLI exists before creating wrapper
        const cliAbsPath = path.join(this.projectRoot, 'src', 'cli.js');
        if (!fs.existsSync(cliAbsPath)) {
            console.error(`❌ CLI not found at: ${cliAbsPath}`);
            console.error('   Please ensure you are in the Fluxus project root directory.');
            process.exit(1);
        }

        const wrapperContent = `#!/usr/bin/env node
/**
 * Fluxus Global Binary Wrapper - Generated by install.js
 * The absolute path to the main CLI is embedded here.
 */
import { resolve } from 'path';

const cliPath = '${cliAbsPath}'; 

async function main() {
    try {
        const { main: cliMain } = await import(cliPath);
        if (typeof cliMain === 'function') {
            cliMain();
        } else {
            console.error('❌ CLI main function not found');
            process.exit(1);
        }
    } catch (error) {
        console.error('❌ Failed to start Fluxus:');
        console.error('   Error:', error.message);
        console.error('   CLI path:', cliPath);
        process.exit(1);
    }
}

main();
`;

        try {
            fs.writeFileSync(targetBin, wrapperContent);
            fs.chmodSync(targetBin, 0o755); 

            console.log(`✅ Fluxus CLI installed successfully!`);
            console.log(`   Command: fluxus`);
            console.log(`   Location: ${targetBin}`);
            
            // ENHANCEMENT: Test the installation
            console.log('🔍 Testing installation...');
            const { execSync } = await import('child_process');
            const version = execSync(`${targetBin} --version`, { encoding: 'utf8' }).trim();
            console.log(`✅ Fluxus ${version} is working!`);
            
            this.globalInstall = true;

        } catch (error) {
            console.error(`❌ Global installation failed.`);
            console.error(`   Error details: ${error.message}`);
            this.globalInstall = false;
        }
    }

    installLocal() {
        console.log(`✅ Local Fluxus installation complete.`);
        console.log(`   Run examples with: node src/cli.js run examples/hello.flux`);
        console.log(`   Or use npm scripts: npm start`);
    }

    createExamples() {
        console.log('📁 Examples are available in ./examples/');
    }

    printPostInstallInstructions() {
        console.log('\n🎉 Fluxus Installation Complete!');
        console.log('\n📚 Quick Start Guide:');
        
        if (this.globalInstall) {
            console.log('   fluxus run examples/hello.flux     # Run a program');
            console.log('   fluxus repl                        # Start interactive mode');
            console.log('   fluxus tutorial                    # Learn the language');
            console.log('   fluxus --help                      # See all commands');
        } else {
            console.log('   node src/cli.js run examples/hello.flux');
            console.log('   node src/cli.js repl');
            console.log('   node src/cli.js tutorial');
            console.log('   node src/cli.js --help');
        }
        
        console.log('\n🧪 Run test suite:');
        console.log('   node test-run.js');
        
        console.log('\n🔧 Reinstall globally later:');
        console.log('   node install.js --global');
    }

    async install() {
        console.log('🚀 Installing Fluxus Language...\n');
        
        // ENHANCEMENT: Install dependencies first
        console.log('📦 Installing dependencies...');
        try {
            const { execSync } = await import('child_process');
            execSync('npm install', { stdio: 'inherit' });
            console.log('✅ Dependencies installed');
        } catch (error) {
            console.log('⚠️  Dependency installation had issues, but continuing...');
        }
        
        if (this.globalInstall) {
            this.installGlobal();
        } else {
            this.installLocal();
        }
        this.createExamples();
        this.printPostInstallInstructions();
    }
}

// Run installation
try {
    const installer = new FluxusInstaller();
    installer.install();
} catch (error) {
    console.error('❌ Installation failed:', error.message);
    process.exit(1);
}
// CI trigger
