#!/usr/bin/env node
// FILENAME: install.js
// Fluxus Language Installation Script - FINAL FIX: Absolute Path Wrapper

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// __dirname is the directory where install.js is located (~/fluxus-lang)
const __dirname = path.dirname(fileURLToPath(import.meta.url));

class FluxusInstaller {
    constructor() {
        // Correctly sets projectRoot to the directory containing install.js
        this.projectRoot = __dirname; 
        this.globalInstall = process.argv.includes('--global');
        this.installDir = this.globalInstall ?
            this.findGlobalInstallDir() :
            this.projectRoot;
    }

    findGlobalInstallDir() {
        // ... (Logic to find writable dir is already correct)
        const possibleDirs = [
            '/data/data/com.termux/files/usr/bin', // Termux specific
            '/usr/local/bin',                      // Standard Linux/macOS
            '/usr/bin',                            // Secondary Linux
            process.env.HOME ? path.join(process.env.HOME, '.local', 'bin') : null,
        ].filter(Boolean);

        for (const dir of possibleDirs) {
            if (fs.existsSync(dir)) {
                try {
                    fs.accessSync(dir, fs.constants.W_OK); 
                    console.log(`📁 Using writable installation directory: ${dir}`);
                    return dir;
                } catch (e) {
                    console.log(`   - Directory exists but is not writable: ${dir}`);
                }
            }
        }
        console.log('⚠️  No writable global directory found. Proceeding with local installation.');
        return this.projectRoot;
    }

    installGlobal() {
        const targetBin = path.join(this.installDir, 'fluxus');
        
        if (this.installDir === this.projectRoot) {
            console.log('❌ Global installation skipped: No writable global directory found.');
            this.globalInstall = false; 
            return;
        }

        // CRITICAL FIX: Generate the wrapper content with the hardcoded absolute path
        const cliAbsPath = path.join(this.projectRoot, 'src', 'cli.js');

        const wrapperContent = `#!/usr/bin/env node
/**
 * Fluxus Global Binary Wrapper - Generated by install.js
 * The absolute path to the main CLI is embedded here.
 */
import { resolve } from 'path';

const cliPath = '${cliAbsPath}'; 

async function main() {
    try {
        const { main: cliMain } = await import(cliPath);
        if (typeof cliMain === 'function') {
            cliMain();
        } else {
            console.error('❌ CLI main function not found');
            process.exit(1);
        }
    } catch (error) {
        console.error('❌ Failed to start Fluxus:');
        console.error('   Error:', error.message);
        console.error('   CLI path:', cliPath);
        process.exit(1);
    }
}

main();
`;

        try {
            // Write the new, path-corrected wrapper file to the global bin path
            fs.writeFileSync(targetBin, wrapperContent);
            
            // Set the executable permission
            fs.chmodSync(targetBin, 0o755); 

            console.log(`✅ Fluxus CLI installed successfully!`);
            console.log(`   Command: fluxus`);
            console.log(`   Location: ${targetBin}`);
            this.globalInstall = true;

        } catch (error) {
            console.error(`❌ Global installation failed.`);
            console.error(`   Error details: ${error.message}`);
            this.globalInstall = false;
        }
    }

    installLocal() {
        console.log(`✅ Local Fluxus installation complete.`);
        console.log(`   Use 'npm start' or 'npm run <command>' to execute.`);
    }

    createExamples() { /* ... */ }

    printPostInstallInstructions() { /* ... */ }

    install() {
        console.log('🚀 Installing Fluxus Language...\n');
        if (this.globalInstall) {
            this.installGlobal();
        } else {
            this.installLocal();
        }
        this.createExamples();
        this.printPostInstallInstructions();
    }
}

// Run installation
try {
    const installer = new FluxusInstaller();
    installer.install();
} catch (error) {
    console.error('❌ Installation failed:', error.message);
    process.exit(1);
}

